### PR TITLE
24.05

### LINKED ISSUE #79: 24.04 release for cachix-flakes?
Hi!

Now that `24.05` is out and stable, it'd be good to get a bump for https://hub.docker.com/r/nixpkgs/cachix-flakes/tags too (happy to try a PR if that helps)

Thanks

### PR DESCRIPTION
**Pull request by domenkozar**
Fixes #79

### CODE REVIEW

**Comment by Mic92** [comment]
```
error: nixVersions.unstable has been removed. For bleeding edge (Nix master, roughly weekly updated) use nixVersions.git, otherwise use nixVersions.latest.
```

**Comment by Mic92** [comment]
cc @zimbatm

**Comment by domenkozar** [comment]
Where does the error come from?

**Comment by zimbatm** [comment]
thanks!

**Comment by zimbatm** [comment]
(the error should be fixed in master now)

**Pull request merged**
