### PR TITLE
feat: added a nixStatic docker image

### PR DESCRIPTION
**Pull request by teto**
an annoying thing about static nix:
```
bash-5.1# nix-env -iA glibc -f https://github.com/NixOS/nixpkgs/archive/23f71e9427c7cd2a6f87a167b4f6dc170b4431df.tar.gz  
unpacking 'https://github.com/NixOS/nixpkgs/archive/23f71e9427c7cd2a6f87a167b4f6dc170b4431df.tar.gz'...
error: attribute 'unsafeDiscardStringContext' missing, at /nix/store/r3n7lyc3sb64qx18ai1qay1gx18c07dy-23f71e9427c7cd2a6f87a167b4f6dc170b4431df.tar.gz/lib/strings.nix:442:13
```

### CODE REVIEW

**Comment by teto** [comment]
@zimbatm passes CI now

**Comment by zimbatm** [comment]
@teto is the image including references to the `/nix/store`? You might have to rewrite the original nix image to clean that up.

**Comment by zimbatm** [comment]
Is the PR ready?

**Comment by teto** [comment]
sadly no sry. I dont have much time to complete it right now. Is it ok to leave it pending ? I can close it anyway. 
IIRC the nix binary works but there are still references to the nix store.

**Comment by zimbatm** [comment]
no worries, let's just leave it like that in case somebody else wants to take over

**Comment by teto** [comment]
good that you could work around this, we are moving our runners towards nixos (which solve most of the problem) si I probably would never have gotten around to finishing this :s

**Comment by zimbatm** [comment]
actually the static nix binary is currently segfaulting when run inside of the container, so it looks like it's not entirely static

**Pull request merged**
