### PR TITLE
images are on docker hub

### PR DESCRIPTION
**Pull request by domenkozar**
cc  @zimbatm

### CODE REVIEW

**Comment by zimbatm** [comment]
It looks like the scarf.sh is broken. It would be nice also to publish them on Github as a fallback.

**Comment by aviaviavi** [comment]
@zimbatm @domenkozar can you share any info about the issue you were seeing? Would like to make sure others are not impacted by this, but currently not seeing any evidence of issues on our side.

**Comment by aviaviavi** [comment]
@domenkozar that looks like a Scarf config issue in the `nix-community` org, at the time I'm writing this, there is no `nixpkgs/caddy` container configured on Scarf. Images that have already been set up are working fine:

```
~/d/mariadb-operator ❯❯❯ docker pull docker.nix-community.org/nixpkgs/cachix                                                                                                    ✘ 2
Using default tag: latest
latest: Pulling from nixpkgs/cachix
9b06fab328d6: Pull complete
Digest: sha256:5fabba1ee4593aafdd9538c89361d08ab29fa79253f71e42ab93331aa95b2f5f
Status: Downloaded newer image for docker.nix-community.org/nixpkgs/cachix:latest
docker.nix-community.org/nixpkgs/cachix:latest
```

If you'd like, you can set up a `Collection` in Scarf so it redirects all traffic on this domain, then caddy would start working as expected. Or if @zimbatm gives the green light, I can set it up for you on my side.

**Comment by zimbatm** [comment]
Sounds good, and then I'll revert the commit!

**Comment by aviaviavi** [comment]
@zimbatm Done!

```
~ ❯❯❯ docker pull docker.nix-community.org/nixpkgs/caddy                                                          ✘ 130
Using default tag: latest
latest: Pulling from nixpkgs/caddy
Digest: sha256:91b26f11d23018f4d04dae8e33a2167ab151d31d4c50547dac9e3c75d5b4bb2a
Status: Image is up to date for docker.nix-community.org/nixpkgs/caddy:latest
docker.nix-community.org/nixpkgs/caddy:latest
```

**Comment by zimbatm** [comment]
thanks, reverted!

**Pull request merged**
