### PR TITLE
bump to nixos-23.05

### LINKED ISSUE #57: Release `nixos-23.05` is missing

### PR DESCRIPTION
**Pull request by fpletz**
The latest release should be available. :smiley: 

Fixes #57.

### CODE REVIEW

**Comment by zimbatm** [comment]
thanks!

**Comment by declension** [comment]
Looks like this failed (see #60?)

**Comment by declension** [comment]
@zimbatm any ideas on how to get 23.05 pushing? :pray: 
We'd really like to use the various images

**Comment by zimbatm** [comment]
fixed!

**Pull request merged**
